/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 import java.awt.Desktop;
 import java.net.URI;
import java.util.ArrayList;
 import javax.swing.JOptionPane;
/**
 *
 * @author Sebastian
 */
public class GUI_componentes extends javax.swing.JFrame {

    /**
     * Creates new form GUI_componentes
     */
    Control miControl = new Control();
    public GUI_componentes() {
        initComponents();
        miControl.limpiarDB();
        miControl.crearNodosCPU();
        miControl.crearNodosCase();
        miControl.crearNodosGPU();
        miControl.crearNodosMotherboards();
        miControl.crearNodosRam();
        miControl.crearNodosDiscoDuro();
        miControl.crearNodosPSU();
        inicializarCBX();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbx_case = new javax.swing.JComboBox();
        detalles_case = new javax.swing.JButton();
        link_case = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cbx_mobo = new javax.swing.JComboBox();
        detalles_mobo = new javax.swing.JButton();
        link_mobo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        cbx_cpu = new javax.swing.JComboBox();
        detalles_cpu = new javax.swing.JButton();
        link_cpu = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        cbx_gpu = new javax.swing.JComboBox();
        detalles_gpu = new javax.swing.JButton();
        link_gpu = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        cbx_ram = new javax.swing.JComboBox();
        detalles_ram = new javax.swing.JButton();
        link_ram = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        cbx_discoDuro = new javax.swing.JComboBox();
        detalles_discoDuro = new javax.swing.JButton();
        link_discoDuro = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        cbx_fuente = new javax.swing.JComboBox();
        detalles_fuente = new javax.swing.JButton();
        link_fuente = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        btnRecomendacion = new javax.swing.JButton();
        btnReestablecer = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Memoria Ram:");

        jLabel2.setText("Case:");

        jLabel3.setText("Motherboard:");

        jLabel4.setText("CPU:");

        jLabel5.setText("GPU:");

        jLabel6.setText("Disco Duro: ");

        jLabel7.setText("Fuente de Poder: ");

        jLabel8.setText("Elige los componentes para tu computadora");

        cbx_case.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_caseItemStateChanged(evt);
            }
        });
        cbx_case.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_caseMouseClicked(evt);
            }
        });
        cbx_case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_caseActionPerformed(evt);
            }
        });

        detalles_case.setText("Ver detalles");
        detalles_case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_caseActionPerformed(evt);
            }
        });

        link_case.setText("Visitar link del producto");
        link_case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_caseActionPerformed(evt);
            }
        });

        cbx_mobo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_moboItemStateChanged(evt);
            }
        });
        cbx_mobo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_moboMouseClicked(evt);
            }
        });
        cbx_mobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_moboActionPerformed(evt);
            }
        });

        detalles_mobo.setText("Ver detalles");
        detalles_mobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_moboActionPerformed(evt);
            }
        });

        link_mobo.setText("Visitar link del producto");
        link_mobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_moboActionPerformed(evt);
            }
        });

        cbx_cpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_cpuMouseClicked(evt);
            }
        });

        detalles_cpu.setText("Ver detalles");
        detalles_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_cpuActionPerformed(evt);
            }
        });

        link_cpu.setText("Visitar link del producto");
        link_cpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_cpuActionPerformed(evt);
            }
        });

        cbx_gpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_gpuMouseClicked(evt);
            }
        });

        detalles_gpu.setText("Ver detalles");
        detalles_gpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_gpuActionPerformed(evt);
            }
        });

        link_gpu.setText("Visitar link del producto");
        link_gpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_gpuActionPerformed(evt);
            }
        });

        cbx_ram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_ramMouseClicked(evt);
            }
        });

        detalles_ram.setText("Ver detalles");
        detalles_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_ramActionPerformed(evt);
            }
        });

        link_ram.setText("Visitar link del producto");
        link_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_ramActionPerformed(evt);
            }
        });

        cbx_discoDuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_discoDuroMouseClicked(evt);
            }
        });

        detalles_discoDuro.setText("Ver detalles");
        detalles_discoDuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_discoDuroActionPerformed(evt);
            }
        });

        link_discoDuro.setText("Visitar link del producto");
        link_discoDuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_discoDuroActionPerformed(evt);
            }
        });

        cbx_fuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_fuenteMouseClicked(evt);
            }
        });

        detalles_fuente.setText("Ver detalles");
        detalles_fuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detalles_fuenteActionPerformed(evt);
            }
        });

        link_fuente.setText("Visitar link del producto");
        link_fuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_fuenteActionPerformed(evt);
            }
        });

        jLabel9.setText("Costo de tu build: ");

        txtCosto.setEditable(false);

        btnRecomendacion.setText("Actualizar Costo");
        btnRecomendacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecomendacionActionPerformed(evt);
            }
        });

        btnReestablecer.setText("Reestablecer");
        btnReestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReestablecerActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(125, 125, 125))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbx_gpu, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(link_gpu, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                                    .addComponent(detalles_gpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addComponent(link_case, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbx_case, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(detalles_case, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbx_discoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(link_discoDuro, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                                .addComponent(detalles_discoDuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(0, 99, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbx_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(link_ram, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(detalles_ram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbx_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(link_fuente, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(detalles_fuente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbx_mobo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(link_mobo, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(detalles_mobo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbx_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(link_cpu, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(detalles_cpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegresar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel8)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(detalles_cpu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(link_cpu)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbx_mobo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalles_mobo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_mobo)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalles_gpu)
                    .addComponent(jLabel5)
                    .addComponent(cbx_gpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(link_gpu)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbx_ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalles_ram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_ram)
                .addGap(30, 30, 30)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx_discoDuro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(detalles_discoDuro))
                .addGap(18, 18, 18)
                .addComponent(link_discoDuro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detalles_case)
                    .addComponent(cbx_case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_case)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbx_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(detalles_fuente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(link_fuente)
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecomendacion)
                    .addComponent(btnReestablecer)
                    .addComponent(jLabel9)
                    .addComponent(btnRegresar))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void inicializarCBX(){
        for(Case c : miControl.CaseList){
            cbx_case.addItem(c.toString());
        }
        for(CPU cpu : miControl.CpuList){
            cbx_cpu.addItem(cpu.toString());
        }
        for(Motherboard m : miControl.MoboList){
            cbx_mobo.addItem(m.toString());
        }
        for(GPU g : miControl.GpuList){
            cbx_gpu.addItem(g.toString());
        }
        for(Ram r : miControl.RamList){
            cbx_ram.addItem(r.toString());
        }
        for(discoDuro d : miControl.discoDuroList){
            cbx_discoDuro.addItem(d.toString());
        }
        for(powerSupply p : miControl.PSUList){
            cbx_fuente.addItem(p.toString());
        }
    }
    public static double round(double value, int places) {
        if (places < 0) throw new IllegalArgumentException();
        long factor = (long) Math.pow(10, places);
        value = value * factor;
        long tmp = Math.round(value);
        return (double) tmp / factor;
    }   
    private void link_caseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_caseActionPerformed
        
        String link=null;
        for(Case c : miControl.CaseList){
            if(cbx_case.getSelectedItem().toString().equals(c.toString())){
                link=c.getLink();
            }
        }
        String cadena = link.replaceAll("\"" , "");
        //System.out.println(cadena);
        try{
            Desktop.getDesktop().browse(new URI(cadena));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la página", null, WIDTH, null);
        }
    }//GEN-LAST:event_link_caseActionPerformed

    private void detalles_caseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_caseActionPerformed
        // TODO add your handling code here:
        String detalles="";
        for(Case c : miControl.CaseList){
            if(cbx_case.getSelectedItem().toString().equals(c.toString())){
                detalles=c.detalles();
            }
        }
        JOptionPane.showMessageDialog(null, detalles);
    }//GEN-LAST:event_detalles_caseActionPerformed

    private void detalles_moboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_moboActionPerformed
        // TODO add your handling code here:
        String detalles="";
        for(Motherboard m : miControl.MoboList){
            if(cbx_mobo.getSelectedItem().toString().equals(m.toString())){
                detalles=m.detalles();
            }
        }
        JOptionPane.showMessageDialog(null, detalles);
    }//GEN-LAST:event_detalles_moboActionPerformed

    private void detalles_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_cpuActionPerformed
        // TODO add your handling code here:
        String detalles="";
        for(CPU cpu : miControl.CpuList){
            if(cbx_cpu.getSelectedItem().toString().equals(cpu.toString())){
                detalles=cpu.detalles();
            }
        }
        JOptionPane.showMessageDialog(null, detalles);
    }//GEN-LAST:event_detalles_cpuActionPerformed

    private void link_cpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_cpuActionPerformed
        // TODO add your handling code here:
        String link=null;
        for(CPU cpu : miControl.CpuList){
            if(cbx_cpu.getSelectedItem().toString().equals(cpu.toString())){
                link=cpu.getLink();
            }
        }
        String cadena = link.replaceAll("\"" , "");
        try{
            Desktop.getDesktop().browse(new URI(cadena));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la página", null, WIDTH, null);
        }
    }//GEN-LAST:event_link_cpuActionPerformed

    private void link_moboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_moboActionPerformed
        // TODO add your handling code here:
        String link=null;
        for(Motherboard m : miControl.MoboList){
            if(cbx_mobo.getSelectedItem().toString().equals(m.toString())){
                link=m.getLink();
            }
        }
        String cadena = link.replaceAll("\"" , "");
        try{
            Desktop.getDesktop().browse(new URI(cadena));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la página", null, WIDTH, null);
        }
    }//GEN-LAST:event_link_moboActionPerformed

    private void detalles_gpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_gpuActionPerformed
        // TODO add your handling code here:
        String detalles="";
        for(GPU g : miControl.GpuList){
            if(cbx_gpu.getSelectedItem().toString().equals(g.toString())){
                detalles=g.detalles();
            }
        }
        JOptionPane.showMessageDialog(null, detalles);        
    }//GEN-LAST:event_detalles_gpuActionPerformed

    private void link_gpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_gpuActionPerformed
        // TODO add your handling code here:
        String link=null;
        for(GPU g : miControl.GpuList){
            if(cbx_gpu.getSelectedItem().toString().equals(g.toString())){
                link=g.getLink();
            }
        }
        String cadena = link.replaceAll("\"" , "");
        try{
            Desktop.getDesktop().browse(new URI(cadena));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la página", null, WIDTH, null);
        }        
    }//GEN-LAST:event_link_gpuActionPerformed

    private void detalles_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_ramActionPerformed
        // TODO add your handling code here:
        String detalles="";
        for(Ram r : miControl.RamList){
            if(cbx_ram.getSelectedItem().toString().equals(r.toString())){
                detalles=r.detalles();
            }
        }
        JOptionPane.showMessageDialog(null, detalles);          
    }//GEN-LAST:event_detalles_ramActionPerformed

    private void link_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_ramActionPerformed
        // TODO add your handling code here:
        String link=null;
        for(Ram r : miControl.RamList){
            if(cbx_gpu.getSelectedItem().toString().equals(r.toString())){
                link=r.getLink();
            }
        }
        String cadena = link.replaceAll("\"" , "");
        try{
            Desktop.getDesktop().browse(new URI(cadena));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la página", null, WIDTH, null);
        }           
    }//GEN-LAST:event_link_ramActionPerformed

    private void detalles_discoDuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_discoDuroActionPerformed
        // TODO add your handling code here:
        String detalles="";
        for(discoDuro d : miControl.discoDuroList){
            if(cbx_discoDuro.getSelectedItem().toString().equals(d.toString())){
                detalles=d.detalles();
            }
        }
        JOptionPane.showMessageDialog(null, detalles);        
    }//GEN-LAST:event_detalles_discoDuroActionPerformed

    private void link_discoDuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_discoDuroActionPerformed
        // TODO add your handling code here:
        String link=null;
        for(discoDuro d : miControl.discoDuroList){
            if(cbx_gpu.getSelectedItem().toString().equals(d.toString())){
                link=d.getLink();
            }
        }
        String cadena = link.replaceAll("\"" , "");
        try{
            Desktop.getDesktop().browse(new URI(cadena));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la página", null, WIDTH, null);
        }           
    }//GEN-LAST:event_link_discoDuroActionPerformed

    private void detalles_fuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detalles_fuenteActionPerformed
        // TODO add your handling code here:
        String detalles="";
        for(powerSupply p : miControl.PSUList){
            if(cbx_fuente.getSelectedItem().toString().equals(p.toString())){
                detalles=p.detalles();
            }
        }
        JOptionPane.showMessageDialog(null, detalles);          
    }//GEN-LAST:event_detalles_fuenteActionPerformed

    private void link_fuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_fuenteActionPerformed
        // TODO add your handling code here:
        String link=null;
        for(powerSupply p : miControl.PSUList){
            if(cbx_gpu.getSelectedItem().toString().equals(p.toString())){
                link=p.getLink();
            }
        }
        String cadena = link.replaceAll("\"" , "");
        try{
            Desktop.getDesktop().browse(new URI(cadena));
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Error al cargar la página", null, WIDTH, null);
        }          
    }//GEN-LAST:event_link_fuenteActionPerformed

    private void cbx_cpuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_cpuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_cpuMouseClicked

    private void cbx_gpuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_gpuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_gpuMouseClicked

    private void cbx_ramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_ramMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_ramMouseClicked

    private void cbx_discoDuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_discoDuroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_discoDuroMouseClicked

    private void cbx_fuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_fuenteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_fuenteMouseClicked

    private void cbx_moboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_moboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_moboMouseClicked

    private void cbx_caseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_caseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_caseMouseClicked

    private void btnRecomendacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecomendacionActionPerformed
        // TODO add your handling code here:
                double costo=0;
        for(CPU c : miControl.CpuList){
            if(cbx_cpu.getSelectedItem().toString().equals(c.toString())){
                costo=costo+c.getPrecio();
            }
        }
        for(Case c : miControl.CaseList){
            if(cbx_case.getSelectedItem().toString().equals(c.toString())){
                costo=costo+c.getPrecio();
            }
        }
        for(GPU g : miControl.GpuList){
            if(cbx_gpu.getSelectedItem().toString().equals(g.toString())){
                costo=costo+g.getPrecio();
            }
        }
        for(Motherboard m : miControl.MoboList){
            if(cbx_mobo.getSelectedItem().toString().equals(m.toString())){
                costo=costo+m.getPrecio();
            }
        }
        for(Ram r : miControl.RamList){
            if(cbx_ram.getSelectedItem().toString().equals(r.toString())){
                costo=costo+r.getPrecio();
            }
        }
        for(discoDuro d : miControl.discoDuroList){
            if(cbx_discoDuro.getSelectedItem().toString().equals(d.toString())){
                costo=costo+d.getPrecio();
            }
        }
        for(powerSupply p : miControl.PSUList){
            if(cbx_fuente.getSelectedItem().toString().equals(p.toString())){
                costo=costo+p.getPrecio();
            }
        }
        
        txtCosto.setText(""+round(costo, 2));
    }//GEN-LAST:event_btnRecomendacionActionPerformed

    private void cbx_caseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_caseItemStateChanged
        // TODO add your handling code here:
             
    }//GEN-LAST:event_cbx_caseItemStateChanged

    private void cbx_moboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_moboItemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cbx_moboItemStateChanged

    private void btnReestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReestablecerActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReestablecerActionPerformed
    
    private void cbx_moboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_moboActionPerformed
        // TODO add your handling code here:
        String CASE="";
        //cbx_case.removeAllItems();
        for(Motherboard m : miControl.MoboList){
            if(cbx_mobo.getSelectedItem().toString().equals(m.toString())){        
              CASE=m.getTipo();
            }
        }
        cbx_case.removeAllItems();
        for(Case c: miControl.CaseList){
            if(c.getTipoMobo().equals(CASE)){
                cbx_case.addItem(c.toString());
            }
        }
        
        String SOCKET="";
        for(Motherboard m : miControl.MoboList){
            if(cbx_mobo.getSelectedItem().toString().equals(m.toString())){
                SOCKET=m.getSocket();
            }
        }
        cbx_cpu.removeAllItems();
        for(CPU c : miControl.CpuList){
            if(c.getSocket().equals(SOCKET)){
                cbx_cpu.addItem(c.toString());
            }
        }
        
        String PCI = "";
        //
        for(Motherboard m : miControl.MoboList){
            if(cbx_mobo.getSelectedItem().toString().equals(m.toString())){
                PCI=m.getPuertoPCI();
            }
        }
        cbx_gpu.removeAllItems();
        for(GPU g : miControl.GpuList){
            if(g.getTipoPCI().equals(PCI)){
                cbx_gpu.addItem(g.toString());
            }
        }
        
        String RAM="";
        //
        for(Motherboard m : miControl.MoboList){
            if(cbx_mobo.getSelectedItem().toString().equals(m.toString())){
                RAM=m.getTipoRam();
            }
        }
        cbx_ram.removeAllItems();
        for(Ram r : miControl.RamList){
            if(r.getTipo().equals(RAM)){
                cbx_ram.addItem(r.toString());
            }
        }
        //System.out.println("JUEM");
    }//GEN-LAST:event_cbx_moboActionPerformed

    private void cbx_caseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_caseActionPerformed
        // TODO add your handling code here:
        /*String MOBO = "";
        for(Case c : miControl.CaseList){
            if(cbx_case.getSelectedItem().toString().equals(c.toString())){
                MOBO=c.getTipoMobo();
            }
        }
        cbx_mobo.removeAllItems();
        for(Motherboard m : miControl.MoboList){
            if(m.getTipo().equals(MOBO)){
                cbx_mobo.addItem(m.toString());
                
            }
        }*/
    }//GEN-LAST:event_cbx_caseActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Main nuevo = new Main();
        nuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_componentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_componentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecomendacion;
    private javax.swing.JButton btnReestablecer;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox cbx_case;
    private javax.swing.JComboBox cbx_cpu;
    private javax.swing.JComboBox cbx_discoDuro;
    private javax.swing.JComboBox cbx_fuente;
    private javax.swing.JComboBox cbx_gpu;
    private javax.swing.JComboBox cbx_mobo;
    private javax.swing.JComboBox cbx_ram;
    private javax.swing.JButton detalles_case;
    private javax.swing.JButton detalles_cpu;
    private javax.swing.JButton detalles_discoDuro;
    private javax.swing.JButton detalles_fuente;
    private javax.swing.JButton detalles_gpu;
    private javax.swing.JButton detalles_mobo;
    private javax.swing.JButton detalles_ram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton link_case;
    private javax.swing.JButton link_cpu;
    private javax.swing.JButton link_discoDuro;
    private javax.swing.JButton link_fuente;
    private javax.swing.JButton link_gpu;
    private javax.swing.JButton link_mobo;
    private javax.swing.JButton link_ram;
    private javax.swing.JTextField txtCosto;
    // End of variables declaration//GEN-END:variables
}
