/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class GUI_Test_de_Personalidad extends javax.swing.JFrame {
    Cliente elclient;

    /**
     * Creates new form GUI_Test_de_Personalidad
     */
    public GUI_Test_de_Personalidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pregunta1 = new javax.swing.ButtonGroup();
        pregunta2 = new javax.swing.ButtonGroup();
        pregunta3 = new javax.swing.ButtonGroup();
        pregunta4 = new javax.swing.ButtonGroup();
        pregunta5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel_pregunta1 = new javax.swing.JPanel();
        rbnSI_pregunta1 = new javax.swing.JRadioButton();
        rbnNO_pregunta1 = new javax.swing.JRadioButton();
        panel_pregunta2 = new javax.swing.JPanel();
        rbnOP1_pregunta2 = new javax.swing.JRadioButton();
        rbnOP2_pregunta2 = new javax.swing.JRadioButton();
        rbnOP3_pregunta2 = new javax.swing.JRadioButton();
        rbnOP4_pregunta2 = new javax.swing.JRadioButton();
        panel_pregunta3 = new javax.swing.JPanel();
        rbnSI_pregunta3 = new javax.swing.JRadioButton();
        rbnNO_pregunta3 = new javax.swing.JRadioButton();
        panel_pregunta4 = new javax.swing.JPanel();
        rbnSI_pregunta4 = new javax.swing.JRadioButton();
        rbnNO_pregunta4 = new javax.swing.JRadioButton();
        panel_pregunta5 = new javax.swing.JPanel();
        rbnSI_pregunta5 = new javax.swing.JRadioButton();
        rbnNO_pregunta5 = new javax.swing.JRadioButton();
        jContinuar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¡ESPERA!");

        jLabel2.setText("Antes de continuar con el programa necesitamos conocerte un poco mas");

        jLabel3.setText("para poder darte las recomendaciones más exactas posibles.");

        jLabel4.setText("¿Sueles viajar frecuentemente?");

        jLabel5.setText("¿Que prefieres hacer con tu tiempo?");

        jLabel6.setText("¿Juzgas un libro por su portada?");

        jLabel7.setText("¿Estás de acuerdo con la frase: \"Mas vale lo viejo conocido que lo nuevo por conocer\"?");

        jLabel8.setText("¿Confías en las compras en línea?");

        pregunta1.add(rbnSI_pregunta1);
        rbnSI_pregunta1.setSelected(true);
        rbnSI_pregunta1.setText("SI");

        pregunta1.add(rbnNO_pregunta1);
        rbnNO_pregunta1.setText("NO");

        javax.swing.GroupLayout panel_pregunta1Layout = new javax.swing.GroupLayout(panel_pregunta1);
        panel_pregunta1.setLayout(panel_pregunta1Layout);
        panel_pregunta1Layout.setHorizontalGroup(
            panel_pregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rbnSI_pregunta1)
                .addGap(18, 18, 18)
                .addComponent(rbnNO_pregunta1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pregunta1Layout.setVerticalGroup(
            panel_pregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pregunta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnSI_pregunta1)
                    .addComponent(rbnNO_pregunta1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pregunta2.add(rbnOP1_pregunta2);
        rbnOP1_pregunta2.setSelected(true);
        rbnOP1_pregunta2.setText("Jugar videojuegos");

        pregunta2.add(rbnOP2_pregunta2);
        rbnOP2_pregunta2.setText("Ver películas y fotos");

        pregunta2.add(rbnOP3_pregunta2);
        rbnOP3_pregunta2.setText("Salir con amigos");

        pregunta2.add(rbnOP4_pregunta2);
        rbnOP4_pregunta2.setText("Terminar tareas/trabajos");

        javax.swing.GroupLayout panel_pregunta2Layout = new javax.swing.GroupLayout(panel_pregunta2);
        panel_pregunta2.setLayout(panel_pregunta2Layout);
        panel_pregunta2Layout.setHorizontalGroup(
            panel_pregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_pregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnOP4_pregunta2)
                    .addComponent(rbnOP3_pregunta2)
                    .addComponent(rbnOP2_pregunta2)
                    .addComponent(rbnOP1_pregunta2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pregunta2Layout.setVerticalGroup(
            panel_pregunta2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbnOP1_pregunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnOP2_pregunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnOP3_pregunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnOP4_pregunta2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pregunta3.add(rbnSI_pregunta3);
        rbnSI_pregunta3.setSelected(true);
        rbnSI_pregunta3.setText("SI");

        pregunta3.add(rbnNO_pregunta3);
        rbnNO_pregunta3.setText("NO");

        javax.swing.GroupLayout panel_pregunta3Layout = new javax.swing.GroupLayout(panel_pregunta3);
        panel_pregunta3.setLayout(panel_pregunta3Layout);
        panel_pregunta3Layout.setHorizontalGroup(
            panel_pregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rbnSI_pregunta3)
                .addGap(18, 18, 18)
                .addComponent(rbnNO_pregunta3)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panel_pregunta3Layout.setVerticalGroup(
            panel_pregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_pregunta3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnSI_pregunta3)
                    .addComponent(rbnNO_pregunta3)))
        );

        pregunta4.add(rbnSI_pregunta4);
        rbnSI_pregunta4.setSelected(true);
        rbnSI_pregunta4.setText("SI");

        pregunta4.add(rbnNO_pregunta4);
        rbnNO_pregunta4.setText("NO");

        javax.swing.GroupLayout panel_pregunta4Layout = new javax.swing.GroupLayout(panel_pregunta4);
        panel_pregunta4.setLayout(panel_pregunta4Layout);
        panel_pregunta4Layout.setHorizontalGroup(
            panel_pregunta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rbnSI_pregunta4)
                .addGap(18, 18, 18)
                .addComponent(rbnNO_pregunta4)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panel_pregunta4Layout.setVerticalGroup(
            panel_pregunta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_pregunta4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnSI_pregunta4)
                    .addComponent(rbnNO_pregunta4)))
        );

        pregunta5.add(rbnSI_pregunta5);
        rbnSI_pregunta5.setSelected(true);
        rbnSI_pregunta5.setText("SI");

        pregunta5.add(rbnNO_pregunta5);
        rbnNO_pregunta5.setText("NO");

        javax.swing.GroupLayout panel_pregunta5Layout = new javax.swing.GroupLayout(panel_pregunta5);
        panel_pregunta5.setLayout(panel_pregunta5Layout);
        panel_pregunta5Layout.setHorizontalGroup(
            panel_pregunta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rbnSI_pregunta5)
                .addGap(18, 18, 18)
                .addComponent(rbnNO_pregunta5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pregunta5Layout.setVerticalGroup(
            panel_pregunta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pregunta5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pregunta5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnSI_pregunta5)
                    .addComponent(rbnNO_pregunta5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jContinuar.setText("Continuar");
        jContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(panel_pregunta2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panel_pregunta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(panel_pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(panel_pregunta5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panel_pregunta4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jContinuar)
                                .addGap(40, 40, 40)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_pregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jContinuar))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinuarActionPerformed
        // TODO add your handling code here:
        String uso = "";
        if (rbnOP1_pregunta2.isSelected()){
            uso = "gaming";
        } else { 
            if (rbnOP2_pregunta2.isSelected()){
                uso = "design";
            }
            else {
                if (rbnOP3_pregunta2.isSelected()){
                    uso = "simple";
                }
            }
        }
        
        
        elclient = new Cliente(rbnSI_pregunta1.isSelected(), rbnSI_pregunta3.isSelected(), rbnSI_pregunta5.isSelected(), uso, rbnSI_pregunta4.isSelected());
    }//GEN-LAST:event_jContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_de_Personalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_de_Personalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_de_Personalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Test_de_Personalidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Test_de_Personalidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_pregunta1;
    private javax.swing.JPanel panel_pregunta2;
    private javax.swing.JPanel panel_pregunta3;
    private javax.swing.JPanel panel_pregunta4;
    private javax.swing.JPanel panel_pregunta5;
    private javax.swing.ButtonGroup pregunta1;
    private javax.swing.ButtonGroup pregunta2;
    private javax.swing.ButtonGroup pregunta3;
    private javax.swing.ButtonGroup pregunta4;
    private javax.swing.ButtonGroup pregunta5;
    private javax.swing.JRadioButton rbnNO_pregunta1;
    private javax.swing.JRadioButton rbnNO_pregunta3;
    private javax.swing.JRadioButton rbnNO_pregunta4;
    private javax.swing.JRadioButton rbnNO_pregunta5;
    private javax.swing.JRadioButton rbnOP1_pregunta2;
    private javax.swing.JRadioButton rbnOP2_pregunta2;
    private javax.swing.JRadioButton rbnOP3_pregunta2;
    private javax.swing.JRadioButton rbnOP4_pregunta2;
    private javax.swing.JRadioButton rbnSI_pregunta1;
    private javax.swing.JRadioButton rbnSI_pregunta3;
    private javax.swing.JRadioButton rbnSI_pregunta4;
    private javax.swing.JRadioButton rbnSI_pregunta5;
    // End of variables declaration//GEN-END:variables
}
